FROM mysql:8.0.36-debian


ENV MYSQL_DATABASE=blogsys \
    MYSQL_ROOT_PASSWORD=rootpass \
    MYSQL_USER=blog_user \
    MYSQL_PASSWORD=blogpass

RUN echo "[mysqld]\nbind-address = 0.0.0.0" > /etc/mysql/conf.d/bind.cnf





