FROM ubuntu:22.04

		
RUN apt-get update && apt-get install -y sudo curl wget bash net-tools acl rsync mysql-client openssh-server vim nano && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 \
    -O /usr/local/bin/yq && chmod +x /usr/local/bin/yq

COPY script/ /usr/local/bin/
RUN chmod +x /usr/local/bin/*

RUN mkdir -p /var/run/sshd
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
RUN ssh-keygen -A

EXPOSE 22
VOLUME ["/storage"]
CMD ["/usr/local/bin/excecute.sh"]
