FROM mysql:8.0.36-debian

RUN apt-get update && \
    apt-get install -y bash mysql-client 

ENV MYSQL_DATABASE=blogsys \
    MYSQL_ROOT_PASSWORD=rootpass \
    MYSQL_USER=blog_user \
    MYSQL_PASSWORD=blogpass

RUN echo "[mysqld]\nbind-address = 0.0.0.0" > /etc/mysql/conf.d/bind.cnf





