FROM nginx:alpine

RUN apk add --no-cache bash


COPY script/nginxgenerator.sh /nginx/nginxgenerator.sh
RUN chmod +x /nginx/nginxgenerator.sh


RUN rm /etc/nginx/conf.d/default.conf


CMD ["/nginx/nginxgenerator.sh"]
