#!/bin/bash


if ! id -nG "$USER" | grep -qw "g_admin"; then
    echo "Access denied. Admins only."
    exit 1
fi


DB="blogsys"
DB_USER="blog_user"
DB_PASS="blogpass"
DB_HOST="db"

declare -A category_map=(
    [1]="Sports"
    [2]="Cinema"
    [3]="Technology"
    [4]="Travel"
    [5]="Food"
    [6]="Lifestyle"
    [7]="Finance"
)

REPORT="/home/admins/${USER}/blog_report_$(date +%Y%m%d).txt"



echo "========================================" >  "$REPORT"
echo "  Blog Platform Admin Report"            >> "$REPORT"
echo "  Generated : $(date)"                   >> "$REPORT"
echo "  Generated by : $USER"                  >> "$REPORT"
echo "========================================" >> "$REPORT"



echo "" >> "$REPORT"
echo "=== System Resources ===" >> "$REPORT"

echo "" >> "$REPORT"
echo "-- Disk Usage --" >> "$REPORT"
df -h /home /var/log 2>/dev/null  >> "$REPORT"

echo "" >> "$REPORT"
echo "-- Load Average --" >> "$REPORT"
echo "$(cat /proc/loadavg | cut -d' ' -f1-3) (1m 5m 15m)" >> "$REPORT"

echo "" >> "$REPORT"
echo "-- System Uptime --" >> "$REPORT"
uptime >> "$REPORT"



#  SERVICE HEALTH


echo "" >> "$REPORT"
echo "=== Service Health ===" >> "$REPORT"
echo "" >> "$REPORT"

# MySQL
if mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" \
    -e "SELECT 1;" "$DB" > /dev/null 2>&1; then
    TABLE_COUNT=$(mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB" \
        -sN -e "SHOW TABLES;" 2>/dev/null | wc -l)
    echo "MySQL        : UP  (tables: $TABLE_COUNT)" >> "$REPORT"
else
    echo "MySQL        : DOWN  <<< ACTION REQUIRED" >> "$REPORT"
fi



# nginx
if curl -s --max-time 3 http://nginx:80 > /dev/null 2>&1; then
    echo "nginx        : UP" >> "$REPORT"
else
    echo "nginx        : DOWN  <<< ACTION REQUIRED" >> "$REPORT"
fi

# SSH
if pgrep sshd > /dev/null 2>&1; then
    echo "SSH          : UP" >> "$REPORT"
else
    echo "SSH          : DOWN  <<< ACTION REQUIRED" >> "$REPORT"
fi



#  PER-AUTHOR DISK USAGE


echo "" >> "$REPORT"
echo "=== Author Disk Usage ===" >> "$REPORT"
echo "" >> "$REPORT"

printf "%-15s %-10s %-8s %-12s\n" \
    "AUTHOR" "DISK" "BLOGS" "PUBLISHED" >> "$REPORT"
echo "--------------------------------------------" >> "$REPORT"

for author_dir in /home/authors/*/; do
    [ -d "$author_dir" ] || continue
    author=$(basename "$author_dir")
    size=$(du -sh "$author_dir" 2>/dev/null | cut -f1)
    blogs=$(ls "$author_dir/blogs/" 2>/dev/null | wc -l)
    published=$(ls "$author_dir/public/" 2>/dev/null | wc -l)
    printf "%-15s %-10s %-8s %-12s\n" \
        "$author" "$size" "$blogs" "$published" >> "$REPORT"
done



echo "" >> "$REPORT"
echo "=== Content Report ===" >> "$REPORT"
echo "" >> "$REPORT"

declare -A published_counts deleted_counts read_counts

for author_dir in /home/authors/*; do
    [ -d "$author_dir" ] || continue
    yaml_file="$author_dir/blogs.yaml"

    if [ -f "$yaml_file" ]; then
        blog_count=$(yq e '.blogs | length' "$yaml_file")
        for ((i=0; i<blog_count; i++)); do
            status=$(yq e ".blogs[$i].publish_status" "$yaml_file")
            if [ "$status" = "true" ]; then
                mapfile -t cids < <(yq e ".blogs[$i].cat_order[]" "$yaml_file")
                for cid in "${cids[@]}"; do
                    ((published_counts[$cid]++))
                done
            fi
        done
    fi

    del_log="$author_dir/deletioncategory.log"
    if [ -f "$del_log" ]; then
        while read -r line; do
            for cid in $line; do
                [ -n "$cid" ] && ((deleted_counts[$cid]++))
            done
        done < "$del_log"
    fi
done

echo "Published Articles by Category:" >> "$REPORT"
for cid in "${!published_counts[@]}"; do
    clean_cid=$(echo "$cid" | xargs)
    category="${category_map[$clean_cid]}"
    echo "  $category: ${published_counts[$cid]}" >> "$REPORT"
done

echo "" >> "$REPORT"
echo "Deleted Articles by Category:" >> "$REPORT"
for cid in "${!deleted_counts[@]}"; do
    category="${category_map[$cid]}"
    echo "  $category: ${deleted_counts[$cid]}" >> "$REPORT"
done

read_log="/var/log/blog_reads.log"
if [ -f "$read_log" ]; then
    while read -r file; do
        ((read_counts["$file"]++))
    done < "$read_log"

    echo "" >> "$REPORT"
    echo "Top 3 Most Read Articles:" >> "$REPORT"
    for file in "${!read_counts[@]}"; do
        echo "${read_counts[$file]} $file"
    done | sort -rn | head -3 \
      | awk '{printf "  %s reads — %s\n", $1, $2}' >> "$REPORT"
else
    echo "" >> "$REPORT"
    echo "No read logs found." >> "$REPORT"
fi



echo "" >> "$REPORT"
echo "=== User Summary ===" >> "$REPORT"
echo "" >> "$REPORT"

AUTHOR_COUNT=$(ls /home/authors/ 2>/dev/null | wc -l)
MOD_COUNT=$(ls /home/mods/ 2>/dev/null | wc -l)
USER_COUNT=$(ls /home/users/ 2>/dev/null | wc -l)
ADMIN_COUNT=$(ls /home/admins/ 2>/dev/null | wc -l)

echo "Authors      : $AUTHOR_COUNT" >> "$REPORT"
echo "Moderators   : $MOD_COUNT"    >> "$REPORT"
echo "Users        : $USER_COUNT"   >> "$REPORT"
echo "Admins       : $ADMIN_COUNT"  >> "$REPORT"

# ── Report Footer ────────────────────────────

echo "" >> "$REPORT"
echo "========================================" >> "$REPORT"
echo "  End of Report"                         >> "$REPORT"
echo "  $(date)"                               >> "$REPORT"
echo "========================================" >> "$REPORT"

echo "Report saved to $REPORT"

